### PR TITLE
Implement subsections depth limit.

### PR DESCRIPTION
**Pull request by kabalin**
Make the permitted depth of subsections configurable at plugin settings (default value 10) and at the course settings.

### CODE REVIEW

**Comment by marinaglancy** [comment]
Hi Ruslan, thanks for this! Can you please change the target branch in this PR to the branch MOODLE_400_STABLE . 
Also there are some failures in automated checks

**Comment by kabalin** [comment]
All CI issues are addressed, thanks.

**Comment by marinaglancy** [comment]
Hi Ruslan, sorry it took so long to review it. I still don't quite understand the purpose of this change, could you describe what problem are you trying to solve?  

There are two comments about the actual patch:
1. I think that per-course setting is an overkill, it is usually the same person who is able to edit course settings and add more sections. Again, maybe I'll understand it better if I know what problem this patch is solving
2. It is still possible to move a section using the "Move" popup to have a nesting level more than the setting.

**Comment by GuiguiWeb** [comment]
Hi @marinaglancy ,

The subsections depth limit (plugin settings) is a requirement for my organization.
Some of our teachers do a lot of sub-section levels. Our students complain of difficulty finding content in this case.

Do you plan to deploy this option?

Best regards,
Guillaume

**Comment by marinaglancy** [comment]
this commit was added as part of https://github.com/marinaglancy/moodle-format_flexsections/pull/54

**Pull request closed without merging**
